name: Generate Docs Test

on:

  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  workflow_dispatch:

jobs:
  generate-doc: 
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout HeliOS...
        uses: actions/checkout@v3

      - name: Install Doxygen and LaTeX...
        shell: bash
        run: |
          sudo apt update
          sudo apt -y install cppcheck

      - name: Run cppcheck
        shell: bash
        run: |
          cppcheck --quiet --language=c --platform=unix64 --max-ctu-depth=8 --cppcheck-build-dir=${{github.workspace}}/build --template="::warning file={file},line={line},col={column}::{message}" --enable=all --std=c89 -DPOSIX_ARCH_OTHER ${{github.workspace}}/src/       

      - name: Not sure
        shell: bash
        run: |
          cat ${{github.workspace}}/src/mem.c