name: Generate Docs Test

on:

  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  workflow_dispatch:

jobs:
  generate-docs: 
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout HeliOS...
        uses: actions/checkout@v3

      - name: Install Doxygen and LaTeX...
        shell: bash
        run: |
          sudo apt update
          sudo apt -y install doxygen-latex

      - name: Create configuration...
        shell: bash
        run: |
          mkdir ${{github.workspace}}/temp          
          doxygen -g ${{github.workspace}}/temp/HeliOS.conf
          sed -i '/^$/d' ${{github.workspace}}/temp/HeliOS.conf
          sed -i '/^#.*/d' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^PROJECT_NAME .*~PROJECT_NAME = HeliOS~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^PROJECT_NUMBER .*~PROJECT_NUMBER = 0.3.5~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^PROJECT_LOGO .*~PROJECT_LOGO = ${{github.workspace}}/extras/HeliOS_OG_Logo.png~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^OUTPUT_DIRECTORY .*~OUTPUT_DIRECTORY = ${{github.workspace}}/temp~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^OPTIMIZE_OUTPUT_FOR_C .*~OPTIMIZE_OUTPUT_FOR_C = YES~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^GENERATE_HTML .*~GENERATE_HTML = NO~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^GENERATE_LATEX .*~GENERATE_LATEX = YES~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^COMPACT_LATEX .*~COMPACT_LATEX = YES~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^GENERATE_RTF .*~GENERATE_RTF = NO~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^GENERATE_MAN .*~GENERATE_MAN = NO~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^GENERATE_XML .*~GENERATE_XML = NO~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^REPEAT_BRIEF .*~REPEAT_BRIEF = NO~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^FULL_PATH_NAMES .*~FULL_PATH_NAMES = NO~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^INPUT .*~INPUT = ${{github.workspace}}/src/config.h ${{github.workspace}}/src/HeliOS.h~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^FILE_PATTERNS .*~FILE_PATTERNS = XXX~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i '/*./d' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^FILE_PATTERNS .*~FILE_PATTERNS = *.h~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^RECURSIVE .*~RECURSIVE = NO~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^CLASS_DIAGRAMS .*~CLASS_DIAGRAMS = NO~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^HAVE_DOT .*~HAVE_DOT = NO~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^PROJECT_BRIEF .*~PROJECT_BRIEF = HeliOS Embedded Operating System~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^SHOW_HEADERFILE .*~SHOW_HEADERFILE = NO~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^SHOW_INCLUDE_FILES .*~SHOW_INCLUDE_FILES = NO~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^QUIET .*~QUIET = YES~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^WARNINGS .*~WARNINGS = YES~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^WARN_LOGFILE .*~WARN_LOGFILE = ${{github.workspace}}/temp/doxygen.log~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^INLINE_SOURCES .*~INLINE_SOURCES = NO~' ${{github.workspace}}/temp/HeliOS.conf
          sed -i 's~^VERBATIM_HEADERS .*~VERBATIM_HEADERS = NO~' ${{github.workspace}}/temp/HeliOS.conf
          cat ${{github.workspace}}/temp/HeliOS.conf

      - name: Resize HeliOS logo...
        shell: bash
        run: |
          convert -resize 100x55! ${{github.workspace}}/extras/HeliOS_OG_Logo.png ${{github.workspace}}/extras/HeliOS_OG_Logo.png

      - name: Generate LaTeX...
        shell: bash
        run: |
          doxygen ${{github.workspace}}/temp/HeliOS.conf
          cat ${{github.workspace}}/temp/doxygen.log
          sed -i 's~^\\begin{center}\%~\\begin{center}\%\n\\includegraphics{HeliOS_OG_Logo.png\n{\\vspace*{1cm}}~' ${{github.workspace}}/temp/latex/refman.tex
          sed -i 's~Generated by Doxygen 1.9.1~HeliOS Developer\x27s Guide~' ${{github.workspace}}/temp/latex/refman.tex
          (tar -zcvf latex.tar.gz ${{github.workspace}}/temp/latex) || true

      - name: Generate PDF from LaTeX...
        shell: bash
        run: |
          cd ${{github.workspace}}/temp/latex
          ls -l
          make
          cd ${{github.workspace}}

      - name: Push PDF to repository...
        shell: bash
        run: |
          cp ${{github.workspace}}/temp/latex/refman.pdf ${{github.workspace}}/doc/HeliOS_Developers_Guide.pdf
          git config --global user.name 'Manny Peterson'
          git config --global user.email '12462046+MannyPeterson@users.noreply.github.com'
          git add ${{github.workspace}}/doc/HeliOS_Developers_Guide.pdf
          git add ${{github.workspace}}/latex.tar.gz
          git commit -m "workflow push"
          git push