name: Generate Docs Test

on:

  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  workflow_dispatch:

jobs:
  generate-docs: 
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout HeliOS...
        uses: actions/checkout@v3

      - name: Install doxygen...
        shell: bash
        run: |
          sudo apt update
          sudo apt install doxygen graphviz ttf-freefont perl build-base texlive-full biblatex ghostscript

      - 

